name: TEA_right
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py38h06a4308_0
  - comm=0.2.1=py38h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - cudnn=8.0.5.39=ha5ca753_1
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - ipykernel=6.28.0=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=11_linux64_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - multicore-tsne=0.1_d4ff4aab=py38hfc89cab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - openssl=3.0.14=h5eee18b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==1.0.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - albucore==0.0.14
      - albumentations==1.4.14
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - astor==0.8.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - autograd==1.3
      - autograd-gamma==0.5.0
      - blessed==1.20.0
      - cachetools==4.2.4
      - captum==0.4.1
      - cffi==1.15.0
      - charset-normalizer==2.0.7
      - click==8.0.3
      - configparser==5.2.0
      - cycler==0.11.0
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - et-xmlfile==1.1.0
      - eval-type-backport==0.2.0
      - executing==2.0.1
      - fasteners==0.19
      - filelock==3.15.4
      - fonttools==4.28.1
      - formulaic==0.2.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - future==0.18.2
      - gitdb==4.0.9
      - gitpython==3.1.24
      - google-auth==2.3.3
      - google-auth-oauthlib==0.4.6
      - googledrivedownloader==0.4
      - gpustat==1.1.1
      - grpcio==1.42.0
      - h5py==3.11.0
      - huggingface-hub==0.26.2
      - idna==3.3
      - imageio==2.35.1
      - importlib-metadata==4.8.2
      - importlib-resources==6.4.4
      - interface-meta==1.2.4
      - ipdb==0.13.13
      - ipython==8.12.3
      - isodate==0.6.0
      - jinja2==3.0.3
      - joblib==1.1.0
      - kiwisolver==1.3.2
      - lazy-loader==0.4
      - lifelines==0.26.3
      - markdown==3.3.6
      - markupsafe==2.0.1
      - matplotlib==3.5.0
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.0.5
      - munch==4.0.0
      - networkx==3.1
      - numcodecs==0.12.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.1.1
      - opencv-python==4.10.0.84
      - openpyxl==3.0.9
      - openslide-python==1.1.2
      - packaging==21.3
      - pandas==1.3.4
      - parmap==1.5.3
      - parso==0.8.4
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==10.4.0
      - pillow-simd==9.0.0.post1
      - pretrainedmodels==0.7.4
      - promise==2.3
      - prompt-toolkit==3.0.47
      - protobuf==3.19.1
      - psutil==5.8.0
      - pure-eval==0.2.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pyparsing==3.0.6
      - python-dateutil==2.8.2
      - python-louvain==0.15
      - pytz==2021.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - rdflib==6.0.2
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - rsa==4.7.2
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.0.1
      - scipy==1.10.1
      - seaborn==0.11.2
      - sentry-sdk==1.5.0
      - setuptools==74.0.0
      - setuptools-scm==6.3.2
      - shapely==2.0.6
      - shortuuid==1.0.8
      - simpleitk==2.4.0
      - smmap==5.0.0
      - spams==2.6.5.4
      - stack-data==0.6.3
      - subprocess32==3.5.4
      - sympy==1.13.2
      - tensorboard==2.7.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - termcolor==1.1.0
      - threadpoolctl==3.0.0
      - tifffile==2023.7.10
      - timm==1.0.11
      - tomli==1.2.2
      - torch==1.7.1+cu110
      - torch-cluster==1.5.9
      - torch-geometric==1.7.1
      - torch-scatter==2.0.7
      - torch-sparse==0.6.9
      - torch-spline-conv==1.2.1
      - torchaudio==0.7.2
      - torchvision==0.8.2+cu110
      - tqdm==4.62.3
      - triton==2.1.0
      - typing-extensions==4.12.2
      - umap==0.1.1
      - urllib3==1.26.7
      - vg==2.0.0
      - wandb==0.12.7
      - wcwidth==0.2.13
      - werkzeug==2.0.2
      - wheel==0.44.0
      - wrapt==1.13.3
      - yacs==0.1.8
      - yarl==1.9.4
      - yaspin==2.1.0
      - zarr==2.16.1
      - zipp==3.6.0
prefix: /home/stat-huamenglei/anaconda3/envs/TEA_right
