name: LKcell
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - affine==2.4.0
      - aiofiles==23.2.1
      - albumentations==1.4.1
      - aliyun-python-sdk-core==2.15.0
      - aliyun-python-sdk-kms==2.16.2
      - annotated-types==0.6.0
      - anyio==4.10.0
      - anykeystore==0.2
      - apex==0.9.10.dev0
      - appdirs==1.4.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - brotli==1.1.0
      - cached-property==1.5.2
      - certifi==2025.8.3
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - chex==0.1.7
      - click==8.1.7
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - colorama==0.4.6
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptacular==1.6.2
      - cryptography==42.0.5
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - etils==1.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.9.0
      - flax==0.7.2
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - geojson==3.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gradio==4.44.1
      - gradio-client==1.3.0
      - greenlet==3.2.4
      - h11==0.16.0
      - histolab==0.7.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.21.4
      - hupper==1.12.1
      - idna==3.4
      - imageio==2.34.0
      - importlib-metadata==7.0.2
      - importlib-resources==6.1.3
      - ipdb==0.13.13
      - ipython==8.18.1
      - jax==0.4.13
      - jaxlib==0.4.13
      - jedi==0.19.2
      - jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-utilities==0.10.1
      - llvmlite==0.41.1
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mmcv==2.1.0
      - mmcv-full==1.7.2
      - mmdet==3.3.0
      - mmengine==0.10.3
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - monai==1.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - munch==4.0.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.0
      - ninja==1.11.1.1
      - numba==0.58.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openslide-python==1.3.1
      - openxlab==0.0.35
      - opt-einsum==3.3.0
      - optax==0.1.8
      - orbax-checkpoint==0.2.3
      - ordered-set==4.1.0
      - orjson==3.11.2
      - oss2==2.17.0
      - packaging==25.0
      - pandarallel==1.6.5
      - pandas==2.0.3
      - parso==0.8.4
      - pastedeploy==3.1.0
      - pbkdf2==1.3
      - pexpect==4.9.0
      - pillow==10.2.0
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - platformdirs==4.3.8
      - pretrainedmodels==0.7.4
      - prettytable==3.10.0
      - prompt-toolkit==3.0.51
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.7
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - python3-openid==3.2.0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - repoze-sendmail==4.4.1
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - ruff==0.12.10
      - safetensors==0.4.2
      - schema==0.7.5
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==1.41.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - shapely==2.0.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - stack-data==0.6.3
      - starlette==0.47.2
      - sympy==1.12
      - tabulate==0.9.0
      - tensorstore==0.1.45
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.3.0
      - tifffile==2023.7.10
      - timm==0.9.16
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchinfo==1.8.0
      - torchmetrics==1.3.1
      - torchstat==0.0.7
      - torchsummary==1.5.1
      - torchvision==0.16.2+cu118
      - tqdm==4.65.2
      - traitlets==5.14.3
      - transaction==5.0
      - translationstring==1.4
      - triton==2.1.0
      - typer==0.16.1
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - ujson==5.9.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - velruse==1.1.1
      - venusian==3.1.1
      - wandb==0.16.4
      - wcwidth==0.2.13
      - webob==1.8.9
      - websockets==12.0
      - wtforms==3.2.1
      - wtforms-recaptcha==0.3.2
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.17.0
      - zope-deprecation==5.1
      - zope-interface==7.2
      - zope-sqlalchemy==3.1
prefix: /home/stat-huamenglei/anaconda3/envs/LKcell
